CREATE DATABASE degree_planner;

USE degree_planner;

CREATE TABLE COURSE (
    cNo VARCHAR(10) NOT NULL,
    cName VARCHAR(50) NOT NULL,
    credit INT NOT NULL,
    offer INT NOT NULL,
    CONSTRAINT coursePK PRIMARY KEY (cNo)
);

CREATE TABLE DEGREE (
    name VARCHAR(40) NOT NULL,
    CONSTRAINT degreePK PRIMARY KEY (name)
);

CREATE TABLE bucket_of_electives (
	dName VARCHAR(40) NOT NULL,
	numOfCourses INT NOT NULL,
	bNo INT NOT NULL,
	CONSTRAINT bNoPK PRIMARY KEY (bNo, dName),
	CONSTRAINT dNameFK FOREIGN KEY (dName) REFERENCES DEGREE(name)
);

CREATE TABLE contains (
	dName VARCHAR(40) NOT NULL,
	cNo VARCHAR(10) NOT NULL,
	bNo INT NOT NULL,
	CONSTRAINT containsPK PRIMARY KEY (bNo, cNo, dName),
	CONSTRAINT bNoFK FOREIGN KEY (bNo) REFERENCES bucket_of_electives(bNo),
	CONSTRAINT cNoFK FOREIGN KEY (cNo) REFERENCES  COURSE(cNo),
	CONSTRAINT cDNameFK FOREIGN KEY (dName) REFERENCES bucket_of_electives(dname)
);

CREATE TABLE prereq (
	prereqCNo VARCHAR(10) NOT NULL,
	cNo VARCHAR(10) NOT NULL,
	v INT, #dummy variable
	CONSTRAINT prereqPK PRIMARY KEY (prereqCNo, cNo),
	CONSTRAINT preCNoFK FOREIGN KEY (prereqCNo) REFERENCES COURSE(cNo),
	CONSTRAINT pCNoFK FOREIGN KEY (cNo) REFERENCES COURSE(cNo)
);

CREATE TABLE required(
	dName VARCHAR(40) NOT NULL,
	cNo VARCHAR(10) NOT NULL,
	v INT, #dummy variable
	CONSTRAINT reqiredPK PRIMARY KEY (dName, cNo),
	CONSTRAINT requiredCNoFK FOREIGN KEY (cNo) REFERENCES COURSE(cNo),
	CONSTRAINT requiredDNameFK FOREIGN KEY (dName) REFERENCES DEGREE(name)
);
