LOAD DATA LOCAL INFILE 'COURSE.csv' REPLACE INTO TABLE COURSE FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'DEGREE.csv' REPLACE INTO TABLE DEGREE FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'prereq.csv' REPLACE INTO TABLE prereq FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'requires.csv' REPLACE INTO TABLE required FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'bucket_of_electives.csv' REPLACE INTO TABLE bucket_of_electives FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'contains.csv' REPLACE INTO TABLE contains FIELDS TERMINATED BY ',';

ALTER TABLE prereq DROP v;
ALTER TABLE required DROP v;

